CREATE TABLE Khoa (
    MaKhoa VARCHAR(2) PRIMARY KEY,
    TenKhoa VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MonHoc (
    MaMH VARCHAR(7) PRIMARY KEY,
    TenMH VARCHAR(100) NOT NULL,
    SoTinChi INT NOT NULL CHECK (SoTinChi > 0)
);

CREATE TABLE QuanTri(
    MaAdmin VARCHAR(4) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    TenDN VARCHAR(20) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL
);

CREATE TABLE Nganh (
    MaNganh VARCHAR(4) PRIMARY KEY,
    TenNganh VARCHAR(100) NOT NULL,
    MaKhoa VARCHAR(2),
    FOREIGN KEY(MaKhoa) REFERENCES Khoa(MaKhoa)
);

CREATE TABLE Lop (
    MaLop VARCHAR(11) PRIMARY KEY,
    TenLop VARCHAR(100) NOT NULL UNIQUE,
    MaNganh VARCHAR(4),
    FOREIGN KEY(MaNganh) REFERENCES Nganh(MaNganh)
);

CREATE TABLE HSO_XETTUYEN (
    MaHS VARCHAR(5) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    CCCD VARCHAR(10) NOT NULL UNIQUE,
    SDT VARCHAR(10) NOT NULL UNIQUE,
    DiaChi VARCHAR(255),
    TruongTHPT VARCHAR(100),
    NamTotNghiep INT
);

CREATE TABLE PT_XetTuyen(
    MaPT VARCHAR(10) PRIMARY KEY,
    MaHS VARCHAR(5),
    MaNganh VARCHAR(4),
    PhuongThuc VARCHAR(100) NOT NULL,
    Diem DECIMAL(4,2) NOT NULL,
    TrangThai VARCHAR(100) NOT NULL DEFAULT 'Cho duyet',
    GhiChu VARCHAR(255),
    MaAdmin VARCHAR(4),
    FOREIGN KEY(MaHS) REFERENCES HSO_XETTUYEN(MaHS),
    FOREIGN KEY(MaNganh) REFERENCES Nganh(MaNganh),
    FOREIGN KEY(MaAdmin) REFERENCES QuanTri(MaAdmin)
);

CREATE TABLE SinhVien (
    MaSV VARCHAR(10) PRIMARY KEY,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    MaLop VARCHAR(11),
    MaHS VARCHAR(5),
    CCCD VARCHAR(10),
    SDT VARCHAR(10),
    FOREIGN KEY (MaLop) REFERENCES Lop(MaLop),
    FOREIGN KEY (MaHS) REFERENCES HSO_XETTUYEN(MaHS)
);

CREATE TABLE ThongBao (
    MaTB VARCHAR(100) PRIMARY KEY,
    NoiDung VARCHAR(100) NOT NULL,
    NgayGui DATE DEFAULT CURRENT_DATE,
    MaAdmin VARCHAR(4),
    FOREIGN KEY(MaAdmin) REFERENCES QuanTri(MaAdmin)
);

CREATE TABLE KQ_HocTap(
    MaSV VARCHAR(10),
    MaMH VARCHAR(7),
    Diem DECIMAL(4,2) NOT NULL,
    FOREIGN KEY(MaSV) REFERENCES SinhVien(MaSV),
    FOREIGN KEY(MaMH) REFERENCES MonHoc(MaMH),
    PRIMARY KEY(MaSV, MaMH)
);

CREATE TABLE TotNghiep (
    MaSV VARCHAR(10) PRIMARY KEY,
    GPA DECIMAL(4,2) NOT NULL CHECK (GPA >=0 AND GPA <=4.0),
    XepLoai VARCHAR(20) NOT NULL,
    FOREIGN KEY(MaSV) REFERENCES SinhVien(MaSV)
);

CREATE TABLE TB_NguoiNhan (
    MaTBNN INT PRIMARY KEY AUTO_INCREMENT,
    MaTB VARCHAR(100),
    MaSV VARCHAR(10),
    TrangThaiDoc TINYINT(1) DEFAULT 0,
    ThoiGianDoc DATE,
    FOREIGN KEY(MaTB) REFERENCES ThongBao(MaTB),
    FOREIGN KEY(MaSV) REFERENCES SinhVien(MaSV)
);
