-- =====================================================
-- QLSVSDH Database Schema
-- MySQL with utf8mb4 charset
-- =====================================================

CREATE TABLE IF NOT EXISTS khoa (
    ma_khoa VARCHAR(20) PRIMARY KEY,
    ten_khoa VARCHAR(255) NOT NULL UNIQUE,
    mo_ta TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS nganh (
    ma_nganh VARCHAR(20) PRIMARY KEY,
    ten_nganh VARCHAR(255) NOT NULL UNIQUE,
    ma_khoa VARCHAR(20),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(ma_khoa) REFERENCES khoa(ma_khoa)
);

CREATE TABLE IF NOT EXISTS lop (
    ma_lop VARCHAR(20) PRIMARY KEY,
    ten_lop VARCHAR(255) NOT NULL UNIQUE,
    ma_nganh VARCHAR(20),
    khoa_hoc VARCHAR(20) NOT NULL DEFAULT '2021',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(ma_nganh) REFERENCES nganh(ma_nganh)
);

CREATE TABLE IF NOT EXISTS mon_hoc (
    ma_mh VARCHAR(20) PRIMARY KEY,
    ten_mh VARCHAR(255) NOT NULL UNIQUE,
    so_tin_chi INT NOT NULL CHECK (so_tin_chi > 0),
    mo_ta TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quan_tri (
    ma_qt VARCHAR(20) PRIMARY KEY,
    ho_ten VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sinh_vien (
    ma_sv VARCHAR(20) PRIMARY KEY,
    ho_ten VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cccd CHAR(10) UNIQUE,
    so_dien_thoai CHAR(10),
    ma_lop VARCHAR(20),
    password_hash VARCHAR(255) NOT NULL,
    gpa FLOAT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(ma_lop) REFERENCES lop(ma_lop)
);

CREATE TABLE IF NOT EXISTS thong_bao (
    ma_tb VARCHAR(20) PRIMARY KEY,
    tieu_de VARCHAR(255),
    noi_dung TEXT NOT NULL,
    nguoi_tao VARCHAR(20),
    doi_tuong VARCHAR(50) NOT NULL DEFAULT 'all',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(nguoi_tao) REFERENCES quan_tri(ma_qt)
);

CREATE TABLE IF NOT EXISTS kq_hoc_tap (
    ma_sv VARCHAR(20),
    ma_mh VARCHAR(20),
    diem FLOAT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(ma_sv) REFERENCES sinh_vien(ma_sv),
    FOREIGN KEY(ma_mh) REFERENCES mon_hoc(ma_mh),
    PRIMARY KEY(ma_sv, ma_mh)
);

CREATE TABLE IF NOT EXISTS tot_nghiep (
    ma_tn VARCHAR(20) PRIMARY KEY,
    ma_sv VARCHAR(20) UNIQUE NOT NULL,
    gpa FLOAT NOT NULL,
    xep_loai VARCHAR(50) NOT NULL,
    du_dieu_kien TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(ma_sv) REFERENCES sinh_vien(ma_sv)
);

CREATE TABLE IF NOT EXISTS tb_nguoi_nhan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ma_tb VARCHAR(20),
    loai_nguoi_nhan VARCHAR(50),
    ma_nguoi_nhan VARCHAR(20),
    da_doc TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY(ma_tb) REFERENCES thong_bao(ma_tb)
);

-- Optional: Additional tables referenced by existing models
CREATE TABLE IF NOT EXISTS pt_xet_tuyen (
    ma_pt VARCHAR(20) PRIMARY KEY,
    ma_nganh VARCHAR(20),
    nam INT,
    chi_tieu INT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tk_xet_tuyen (
    ma_tk VARCHAR(20) PRIMARY KEY,
    ma_sv VARCHAR(20),
    ma_pt VARCHAR(20),
    diem_xet_tuyen FLOAT,
    trang_thai VARCHAR(20),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS hso_xet_tuyen (
    ma_hso VARCHAR(20) PRIMARY KEY,
    ma_tk VARCHAR(20),
    nguyen_vong INT,
    trang_thai VARCHAR(20),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
